// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile" validate:"required,len=11,mobile"`
	Password string `json:"password" validate:"min=6,max=20"`
}

type RegisterResp struct {
	Id           int64  `json:"id"`
	Mobile       string `json:"mobile"`
	Nickname     string `json:"nickname"`
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type LoginReq struct {
	Mobile   string `json:"mobile" validate:"required,len=11,mobile"`
	Password string `json:"password" validate:"min=6,max=20"`
}

type LoginResp struct {
	Id           int64  `json:"id"`
	Mobile       string `json:"mobile"`
	Nickname     string `json:"nickname"`
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UserInfoReq struct {
	Id int64 `path:"id"`
}

type UserInfoResp struct {
	User
}
